version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: sinf
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - mongo

  server:
    container_name: server
    build: ./server/
    image: server:latest
    ports:
      - '3001:3001'
    volumes:
      - ./server/assets:/app/assets
      - ./server/config:/app/config
      - ./server/logs:/app/logs
      - ./server/mongodb:/app/mongodb
      - ./server/parser:/app/parser
      - ./server/routes:/app/routes
      - ./server/store:/app/store
      - ./server/utils:/app/utils
      - ./server/app.js:/app/app.js
    environment:
      - WAIT_HOSTS= mongodb:27017
      - NODE_ENV=development
    depends_on:
      - mongo
      - mongo-express

